version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  db:
    restart: 
      always
    image: postgres
    env_file:
      - .env
    volumes:
      - local_postgres_data:/var/lib/postgresql/data # local_db_path to docker postgres data folder
      - local_postgres_data_backups:/backups # postgres backup db
    ports: 
      - "5432"

  backend:
    links:
      - db
    image: thumbs_up_news_backend
    build:
      context: ./thumbsupnews_backend
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/thumbsupnews
    ports:
      - "8000:8000"

  frontend:
    ports:
      - 3000:3000
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - ./frontend/.env
    command: npm run start